# Generated by Django 3.2.3 on 2021-07-09 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingusers',
            name='courses',
        ),
    ]
