# Generated by Django 3.2.4 on 2021-07-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20210708_1324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PendingUsers',
        ),
    ]
