# Generated by Django 3.2.4 on 2021-07-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_delete_pendingusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('collegeid', models.CharField(max_length=5)),
                ('enrollmentnumber', models.CharField(max_length=10)),
                ('yearofjoin', models.IntegerField()),
                ('contact', models.IntegerField(blank=True)),
                ('idproof', models.ImageField(upload_to='id_pics')),
            ],
        ),
    ]
