# Generated by Django 3.2.4 on 2021-07-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_pendingusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingusers',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pendingusers',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
